# This is a basic workflow to help you get started with Actions
name: PHP Linting
on: 
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master

    