# This is a basic workflow to help you get started with Actions

name: PHP Linting
on: pull_request
jobs:

  build-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2
      - uses: php-actions/phpstan@v2
    